---
- name: Restart all Docker containers on remote server
  hosts: docker_hosts
  become: yes
  tasks:

    - name: Get list of running container IDs
      command: docker ps -q
      register: running_containers
      changed_when: false

    - name: Restart running containers
      command: docker restart {{ item }}
      loop: "{{ running_containers.stdout_lines }}"
      when: running_containers.stdout_lines | length > 0
      register: restarted_containers
      changed_when: restarted_containers is defined
