---
- name: Prune Docker containers and images
  hosts: docker_hosts
  become: true
  collections:
    - community.docker
  tasks:
    - name: Prune containers
      community.docker.docker_prune:
        containers: yes

    - name: Prune images
      community.docker.docker_prune:
        images: yes
        images_filters:
          dangling: true

    - name: Prune volumes
      community.docker.docker_prune:
        volumes: yes

    - name: Prune build cache
      community.docker.docker_prune:
        builder_cache: yes
