---
- name: Install qemu-guest-agent on Debian Machines
  hosts: linux  # Update with your actual host group
  become: yes  # Run as root

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install qemu-guest-agent package
      apt:
        name: qemu-guest-agent
        state: present

    - name: Enable and start qemu-guest-agent service
      systemd:
        name: qemu-guest-agent
        enabled: yes
        state: started

    - name: Verify qemu-guest-agent is running
      command: systemctl status qemu-guest-agent
      register: agent_status
      changed_when: false

    - name: Display service status
      debug:
        msg: "{{ agent_status.stdout }}"
