---
- name: Install Windows Applications
  hosts: windows
  tasks:

    - name: Notepad++ 
      win_chocolatey:
        name: notepadplusplus
        state: present

    - name: FireFox
      win_chocolatey:
        name: firefox
        state: present